version: '3'
services:
  demark-world:
    image: llinkedlist/sorawm:latest
    container_name: demark_world_container
    ports:
      - 8501:8501
    command: streamlit run app.py --server.port 8501
    environment:
      - PYTHONPATH=/workspace/src:/workspace
    volumes:
      - ./:/workspace
      - ./.cache:/root/.cache
      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    stdin_open: true
    working_dir: /workspace
    shm_size: '16gb'

volumes:
  huggingface_cache:
